# Site settings
title: Redmerald &#183; A simple Jekyll theme
description: "A minimal blog template, built with Jekyll."
url: "http://github.com/Vesuvium/redmerald"
author:
  name: "Vesuvium"
  url: "http://github.com/Vesuvium"


# Build settings
baseurl: /redmerald/ # Change this to your relative path (ex: /blog/), or leave just a /
markdown: kramdown
source: .
destination: ./_site
permalink: /:title
paginate: 5
paginate_path: /page:num/

# Default values
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Custom variables
# This section holds all the custom variables that are used by this
# theme.
version: "1.1.0"
lang: "en"
subtitle: "A Jekyll theme"

navigation:
  - title: Home
    url: index
  - title: About
    url: about



# Options
reverse: true
